apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mydb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-rwo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpidb
spec:
  selector:
    matchLabels:
      app: glpidb
  template:
    metadata:
      labels:
        app: glpidb
    spec:
      containers:
      - image: eveigadev/k8s-glpidb:latest
        args:
        - "--ignore-db-dir=lost+found"
        name: glpidb
        ports:
        - containerPort: 3306
          name: glpidb

        volumeMounts:
        - name: mydb
          mountPath: /var/lib/mysql/
      volumes:
      - name: mydb
        persistentVolumeClaim:
          claimName: mydb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glpi
  labels:
    app: glpi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: glpi
  template:
    metadata:
      labels:
        app: glpi
    spec:
      containers:
      - name: glpi
        image: eveigadev/k8s-glpi:latest
        #imagePullPolicy: Always
        ports:
        - containerPort: 80
