apiVersion: v1
kind: Service
metadata:
  name: glpi
spec:
  selector:
    app: glpi
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: glpidb
spec:
  ports:
  - port: 3306
  selector:
    app: glpidb

